from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

def add_overlay(base_image_bytes: bytes, hook: str, subtitle: str = "") -> bytes:
    img = Image.open(BytesIO(base_image_bytes)).convert("RGBA")
    
    draw = ImageDraw.Draw(img)
    
    # Fonts (fallback to default if not found)
    try:
        font_large = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 80)  # Common in containers
        font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 40)
    except:
        font_large = ImageFont.load_default().font_variant(size=80)
        font_small = ImageFont.load_default().font_variant(size=40)
    
    # Semi-transparent dark overlay for readability
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 140))
    img = Image.alpha_composite(img, overlay)
    draw = ImageDraw.Draw(img)
    
    # Center text
    w, h = img.size
    draw.text((w//2, h//3), hook.upper(), font=font_large, fill="white", anchor="mm", stroke_width=4, stroke_fill="black")
    if subtitle:
        draw.text((w//2, h//2 + 50), subtitle, font=font_small, fill="#a0a0ff", anchor="mm")
    
    # Branding footer
    draw.text((w//2, h - 80), "Generated by NewsAgent Pro", font=font_small, fill="#8080ff", anchor="mm")
    
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()
